### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by mikeedi** [yeyang1021/ParamNet-HNET-#1]
Can you upload weights, please?

**Comment by yeyang1021** [comment]
Ok, I will upload it, tomorrow.

**Comment by yeyang1021** [comment]
You can download it using the following URL.
[https://pan.baidu.com/s/1a2w5pHbGWagjZZ3qsyaZAw]
password: 985s

**Comment by mikeedi** [comment]
Sorry but Baidu is stronger than me. I couldn't download that, I'm really tried hard(((

**Comment by yeyang1021** [comment]
Ok, I will try to upload it using google drive.

**Comment by yeyang1021** [comment]
Google drive :   https://drive.google.com/open?id=1Kkf5oHB10NZwgjfSezWgfEMCygMkwNes
